/**
 * Cisnet WinPurify Pro - Automatic Version Synchronizer & Patch Note Reader
 * Reads the latest version tag from docs/PATCH_NOTES.md or DOC/PATCH_NOTES.md
 * Updates metadata.json, package.json, and WinPurifyPro.csproj
 */

const fs = require('fs');
const path = require('path');

function getLatestVersionFromPatchNotes() {
  const patchNotePaths = [
    path.resolve(__dirname, 'docs', 'PATCH_NOTES.md'),
    path.resolve(__dirname, 'DOC', 'PATCH_NOTES.md')
  ];

  for (const p of patchNotePaths) {
    if (fs.existsSync(p)) {
      const content = fs.readFileSync(p, 'utf8');
      // Match patterns like: ## 📌 [v3.0.4] or ## [v3.0.4] or [3.0.4]
      const match = content.match(/\[v?(\d+\.\d+\.\d+(?:\.\d+)?)\]/i);
      if (match && match[1]) {
        // Ensure DOC directory stays in sync if exists
        const docDir = path.resolve(__dirname, 'DOC');
        const targetDocPath = path.resolve(docDir, 'PATCH_NOTES.md');
        if (p.includes('docs') && fs.existsSync(docDir)) {
          try {
            fs.copyFileSync(p, targetDocPath);
          } catch(e) {}
        }
        return match[1];
      }
    }
  }

  return '3.0.4'; // Fallback
}

function syncVersion() {
  const versionStr = getLatestVersionFromPatchNotes();
  const semverStr = versionStr.split('.').slice(0, 3).join('.');
  const assemblyVerStr = versionStr.includes('.', 3) ? versionStr : `${semverStr}.0`;

  console.log(`[Version Sync] Extracted version from PATCH_NOTES.md: v${semverStr} (Assembly: ${assemblyVerStr})`);

  // 1. Sync metadata.json
  const metadataPath = path.resolve(__dirname, 'metadata.json');
  if (fs.existsSync(metadataPath)) {
    try {
      const meta = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
      meta.version = assemblyVerStr;
      if (meta.description) {
        meta.description = meta.description.replace(/v\d+\.\d+(\.\d+)?/g, `v${semverStr}`);
      }
      fs.writeFileSync(metadataPath, JSON.stringify(meta, null, 2), 'utf8');
      console.log(`[Version Sync] Updated metadata.json -> version: ${assemblyVerStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating metadata.json:', e.message);
    }
  }

  // 2. Sync package.json
  const packageJsonPath = path.resolve(__dirname, 'package.json');
  if (fs.existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      pkg.version = semverStr;
      if (pkg.description) {
        pkg.description = pkg.description.replace(/v\d+\.\d+(\.\d+)?/g, `v${semverStr}`);
      }
      fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2), 'utf8');
      console.log(`[Version Sync] Updated package.json -> version: ${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating package.json:', e.message);
    }
  }

  // 3. Sync WinPurifyPro.csproj & WinPurifyCommander.csproj
  const csprojPaths = [
    path.resolve(__dirname, 'WinPurifyPro.csproj'),
    path.resolve(__dirname, 'WinPurifyCommander.csproj')
  ];
  for (const csprojPath of csprojPaths) {
    if (fs.existsSync(csprojPath)) {
      try {
        let content = fs.readFileSync(csprojPath, 'utf8');
        content = content
          .replace(/<Version>.*?<\/Version>\s*\r?\n?/g, '')
          .replace(/<AssemblyVersion>.*?<\/AssemblyVersion>\s*\r?\n?/g, '')
          .replace(/<FileVersion>.*?<\/FileVersion>\s*\r?\n?/g, '')
          .replace(/<InformationalVersion>.*?<\/InformationalVersion>\s*\r?\n?/g, '');

        content = content.replace(
          '<PropertyGroup>',
          `<PropertyGroup>\n    <Version>${semverStr}</Version>\n    <AssemblyVersion>${assemblyVerStr}</AssemblyVersion>\n    <FileVersion>${assemblyVerStr}</FileVersion>\n    <InformationalVersion>${semverStr} (AhBiYout)</InformationalVersion>`
        );
        fs.writeFileSync(csprojPath, content, 'utf8');
        console.log(`[Version Sync] Updated ${path.basename(csprojPath)} -> AssemblyVersion: ${assemblyVerStr}, InformationalVersion: ${semverStr}`);
      } catch(e) {
        console.error(`[Version Sync Error] Failed updating ${path.basename(csprojPath)}:`, e.message);
      }
    }
  }

  // 4. Sync src/version.ts
  const versionTsPath = path.resolve(__dirname, 'src', 'version.ts');
  try {
    fs.writeFileSync(
      versionTsPath,
      `// Auto-generated by sync-version.js from docs/PATCH_NOTES.md\nexport const APP_VERSION = '${semverStr}';\n`,
      'utf8'
    );
    console.log(`[Version Sync] Updated src/version.ts -> APP_VERSION = '${semverStr}'`);
  } catch(e) {
    console.error('[Version Sync Error] Failed updating src/version.ts:', e.message);
  }

  // 5. Sync version.rc (C++ Resource Version)
  const versionRcPath = path.resolve(__dirname, 'version.rc');
  if (fs.existsSync(versionRcPath)) {
    try {
      const parts = semverStr.split('.');
      const vMajor = parts[0] || '1';
      const vMinor = parts[1] || '0';
      const vPatch = parts[2] || '0';
      const rcVersionComma = `${vMajor},${vMinor},${vPatch},0`;
      const rcVersionStr = `${vMajor}.${vMinor}.${vPatch}.0`;

      let rcContent = fs.readFileSync(versionRcPath, 'utf8');
      rcContent = rcContent
        .replace(/#define VER_FILEVERSION\s+[\d,]+/g, `#define VER_FILEVERSION             ${rcVersionComma}`)
        .replace(/#define VER_FILEVERSION_STR\s+"[^"]*"/g, `#define VER_FILEVERSION_STR         "${rcVersionStr}\\0"`)
        .replace(/#define VER_PRODUCTVERSION\s+[\d,]+/g, `#define VER_PRODUCTVERSION          ${rcVersionComma}`)
        .replace(/#define VER_PRODUCTVERSION_STR\s+"[^"]*"/g, `#define VER_PRODUCTVERSION_STR       "${semverStr}\\0"`);

      fs.writeFileSync(versionRcPath, rcContent, 'utf8');
      console.log(`[Version Sync] Updated version.rc -> ${rcVersionStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating version.rc:', e.message);
    }
  }

  // 6. Sync build.ps1 & build.bat
  const buildPs1Path = path.resolve(__dirname, 'build.ps1');
  if (fs.existsSync(buildPs1Path)) {
    try {
      let ps1Content = fs.readFileSync(buildPs1Path, 'utf8');
      ps1Content = ps1Content.replace(/WinPurify Pro v\d+\.\d+(\.\d+)?/g, `WinPurify Pro v${semverStr}`);
      ps1Content = ps1Content.replace(/\$setupFilename = "WinPurifyPro_v[^_]+_/g, `$setupFilename = "WinPurifyPro_v${semverStr}_`);
      ps1Content = ps1Content.replace(/\r?\n/g, '\r\n');
      fs.writeFileSync(buildPs1Path, ps1Content, 'utf8');
      console.log(`[Version Sync] Updated build.ps1 -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating build.ps1:', e.message);
    }
  }

  const buildBatPath = path.resolve(__dirname, 'build.bat');
  if (fs.existsSync(buildBatPath)) {
    try {
      let batContent = fs.readFileSync(buildBatPath, 'utf8');
      batContent = batContent.replace(/WinPurify Pro v\d+\.\d+(\.\d+)?/g, `WinPurify Pro v${semverStr}`);
      batContent = batContent.replace(/set "APP_VERSION=[^"]*"/g, `set "APP_VERSION=${semverStr}"`);
      // Ensure CRLF line endings for Windows cmd.exe compatibility
      batContent = batContent.replace(/\r?\n/g, '\r\n');
      fs.writeFileSync(buildBatPath, batContent, 'utf8');
      console.log(`[Version Sync] Updated build.bat -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating build.bat:', e.message);
    }
  }

  // 6.5 Sync app.manifest assemblyIdentity
  const appManifestPath = path.resolve(__dirname, 'app.manifest');
  if (fs.existsSync(appManifestPath)) {
    try {
      let manifestContent = fs.readFileSync(appManifestPath, 'utf8');
      manifestContent = manifestContent.replace(/version="\d+\.\d+\.\d+\.\d+"/g, `version="${assemblyVerStr}"`);
      fs.writeFileSync(appManifestPath, manifestContent, 'utf8');
      console.log(`[Version Sync] Updated app.manifest -> version: ${assemblyVerStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating app.manifest:', e.message);
    }
  }

  // 6.6 Sync CommanderMainWindow.xaml title & badge
  const commanderXamlPath = path.resolve(__dirname, 'CommanderMainWindow.xaml');
  if (fs.existsSync(commanderXamlPath)) {
    try {
      let xamlContent = fs.readFileSync(commanderXamlPath, 'utf8');
      xamlContent = xamlContent.replace(/Central Commander Console v\d+\.\d+(\.\d+)?/g, `Central Commander Console v${semverStr}`);
      xamlContent = xamlContent.replace(/<TextBlock Text="v\d+\.\d+(\.\d+)?" FontSize="10" FontWeight="Bold" Foreground="#DDD6FE"/g, `<TextBlock Text="v${semverStr}" FontSize="10" FontWeight="Bold" Foreground="#DDD6FE"`);
      fs.writeFileSync(commanderXamlPath, xamlContent, 'utf8');
      console.log(`[Version Sync] Updated CommanderMainWindow.xaml -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating CommanderMainWindow.xaml:', e.message);
    }
  }

  // 7. Sync ViewModels/MainViewModel.cs default fallback string if present
  const mainViewModelPath = path.resolve(__dirname, 'ViewModels', 'MainViewModel.cs');
  if (fs.existsSync(mainViewModelPath)) {
    try {
      let vmContent = fs.readFileSync(mainViewModelPath, 'utf8');
      vmContent = vmContent.replace(/: "\d+\.\d+\.\d+";/g, `: "${semverStr}";`);
      fs.writeFileSync(mainViewModelPath, vmContent, 'utf8');
      console.log(`[Version Sync] Updated ViewModels/MainViewModel.cs -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating MainViewModel.cs:', e.message);
    }
  }

  // 7.5 Sync Services/AppEnvironment.cs default fallback string if present
  const appEnvironmentPath = path.resolve(__dirname, 'Services', 'AppEnvironment.cs');
  if (fs.existsSync(appEnvironmentPath)) {
    try {
      let envContent = fs.readFileSync(appEnvironmentPath, 'utf8');
      envContent = envContent.replace(/: "\d+\.\d+\.\d+";/g, `: "${semverStr}";`);
      fs.writeFileSync(appEnvironmentPath, envContent, 'utf8');
      console.log(`[Version Sync] Updated Services/AppEnvironment.cs -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating Services/AppEnvironment.cs:', e.message);
    }
  }

  // 8. Sync installer.iss (Inno Setup 6 Script Version)
  const installerIssPath = path.resolve(__dirname, 'installer.iss');
  if (fs.existsSync(installerIssPath)) {
    try {
      let issContent = fs.readFileSync(installerIssPath, 'utf8');
      issContent = issContent.replace(/#define MyAppVersion "[^"]*"/g, `#define MyAppVersion "${semverStr}"`);
      fs.writeFileSync(installerIssPath, issContent, 'utf8');
      console.log(`[Version Sync] Updated installer.iss -> MyAppVersion "${semverStr}"`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating installer.iss:', e.message);
    }
  }

  // 9. Sync index.html (Meta Description and Title)
  const indexHtmlPath = path.resolve(__dirname, 'index.html');
  if (fs.existsSync(indexHtmlPath)) {
    try {
      let htmlContent = fs.readFileSync(indexHtmlPath, 'utf8');
      htmlContent = htmlContent.replace(/WinPurify Pro v\d+\.\d+(\.\d+)?/g, `WinPurify Pro v${semverStr}`);
      fs.writeFileSync(indexHtmlPath, htmlContent, 'utf8');
      console.log(`[Version Sync] Updated index.html -> v${semverStr}`);
    } catch(e) {
      console.error('[Version Sync Error] Failed updating index.html:', e.message);
    }
  }

  return semverStr;
}

if (require.main === module) {
  const v = syncVersion();
  // Print for bash / cmd script capturing
  process.stdout.write(v);
} else {
  module.exports = { getLatestVersionFromPatchNotes, syncVersion };
}
