export interface ModuleItem {
  seq: number;
  id: string;
  name: string;
  category: string;
  subCategory?: "Account" | "FactoryReset" | "Profile" | "Forensics";
  risk: "Safe" | "Deep" | "Risky";
  estimatedKb: number;
  description: string;
  selected: boolean;
  status: "Pending" | "Scanning" | "Optimizing" | "Done";
}

export const INITIAL_MODULES: ModuleItem[] = [
  {
    "seq": 1,
    "id": "pri-telemetry",
    "name": "진단/텔레메트리 데이터",
    "description": "Windows 진단 및 원격 측정 설정 잔여 캐시 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 17548
  },
  {
    "seq": 2,
    "id": "pri-quick-access",
    "name": "바로 가기 / 최근 항목",
    "description": "탐색기 바로 가기 및 최근 접근 파일 링크 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 24892
  },
  {
    "seq": 3,
    "id": "pri-search-history",
    "name": "Windows 검색 기록",
    "description": "작업 표시줄 및 시작 메뉴 검색 키워드 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 9076
  },
  {
    "seq": 4,
    "id": "pri-shell-bags",
    "name": "폴더 뷰(Shell Bags) 초기화",
    "description": "탐색기 폴더 위치 및 크기 캐시 레지스트리 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 49728
  },
  {
    "seq": 5,
    "id": "pri-jump-lists",
    "name": "작업 표시줄 점프 목록",
    "description": "작업 표시줄 아이콘 우클릭 시 표시되는 최근 고정 목록 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 26650
  },
  {
    "seq": 6,
    "id": "pri-run-mru",
    "name": "실행/검색 MRU 기록",
    "description": "Windows 실행(Win+R) 대화상자 명령어 입력 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29088
  },
  {
    "seq": 7,
    "id": "pri-recent-docs",
    "name": "레지스트리 최근 문서 목록",
    "description": "레지스트리에 기록된 최근 열어본 문서 참조 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 47523
  },
  {
    "seq": 8,
    "id": "pri-clipboard",
    "name": "클립보드 기록 비우기",
    "description": "시스템 클립보드에 복사된 텍스트 및 미디어 캐시 소거",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 1804
  },
  {
    "seq": 9,
    "id": "pri-typed-paths",
    "name": "탐색기 주소창 입력 기록",
    "description": "파일 탐색기 상단 주소 표시줄에 직접 타이핑한 경로 목록 소거",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 43238
  },
  {
    "seq": 10,
    "id": "pri-user-assist",
    "name": "UserAssist 앱 실행 통계",
    "description": "Windows 내부에서 앱 실행 빈도를 암호화 기록하는 UserAssist 키 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 3072
  },
  {
    "seq": 11,
    "id": "pri-activity-timeline",
    "name": "활동 타임라인 기록",
    "description": "Windows 타임라인 사용자 활동 기록 및 캐시 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 6582
  },
  {
    "seq": 12,
    "id": "pri-office-mru",
    "name": "Office 최근 사용 목록",
    "description": "Microsoft Office 제품군의 최근 열어본 파일 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 47802
  },
  {
    "seq": 13,
    "id": "pri-winrar-mru",
    "name": "WinRAR 압축 해제 기록",
    "description": "WinRAR에서 최근 압축/해제한 파일 및 폴더 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 30119
  },
  {
    "seq": 14,
    "id": "pri-paint-mru",
    "name": "그림판 최근 목록",
    "description": "그림판 앱의 최근 작업 이미지 파일 목록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 3448
  },
  {
    "seq": 15,
    "id": "pri-wordpad-mru",
    "name": "워드패드 최근 목록",
    "description": "워드패드 앱의 최근 작업 문서 목록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 20565
  },
  {
    "seq": 16,
    "id": "pri-wallpaper-mru",
    "name": "배경화면 변경 기록",
    "description": "설정 앱의 배경화면 최근 선택 기록 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 31811
  },
  {
    "seq": 17,
    "id": "pri-explorer-breadcrumb",
    "name": "탐색기 이동 경로 캐시",
    "description": "탐색기 상단 브레드크럼 네비게이션 캐시 정리",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29791
  },
  {
    "seq": 18,
    "id": "pri-taskbar-mru",
    "name": "작업 표시줄 고정 링크 정리",
    "description": "작업 표시줄 핀 고정 바로가기 캐시 초기화",
    "category": "Privacy",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 40331
  },
  {
    "seq": 19,
    "id": "pri-thumb-global",
    "name": "전체 썸네일 데이터베이스",
    "description": "손상되었거나 누적된 탐색기 미리보기 썸네일 DB 파일 일괄 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 15419
  },
  {
    "seq": 20,
    "id": "pri-generic-mru-list",
    "name": "범용 최근 사용 목록",
    "description": "기타 서드파티 및 시스템 공통 MRU 레지스트리 잔여 기록 소거",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 12559
  },
  {
    "seq": 21,
    "id": "pri-cred-vault",
    "name": "Windows 자격 증명 관리자 & Vault 완전 소거",
    "description": "Windows 자격 증명 관리자 및 Vault에 저장된 웹/네트워크/원격 로그인 계정 전체 소거",
    "category": "Privacy",
    "risk": "Deep",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 32401
  },
  {
    "seq": 22,
    "id": "pri-rdp-history",
    "name": "원격 데스크톱 (MSTSC / RDP) 접속 이력",
    "description": "MSTSC 원격 데스크톱 연결에 저장된 이전 서버 IP, 접속 기록 및 Default.rdp 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 16585
  },
  {
    "seq": 23,
    "id": "pri-usbstor-history",
    "name": "USB 저장장치 연결 포렌식 이력",
    "description": "과거 시스템에 연결되었던 USB 메모리/외장하드 일련번호 및 연결 장치 히스토리 소거",
    "category": "Privacy",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 23939
  },
  {
    "seq": 24,
    "id": "pri-bam-dam-history",
    "name": "BAM/DAM 프로세스 실행 통계 이력",
    "description": "Background Activity Moderator에 기록된 모든 실행 파일(.exe) 전체 경로와 타임스탬프 초기화",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 42252
  },
  {
    "seq": 25,
    "id": "pri-comdlg32-opensave",
    "name": "파일 열기/저장 다이얼로그 MRU",
    "description": "모든 프로그램의 '열기'/'다른 이름으로 저장' 창에서 접근했던 폴더 및 파일 경로 기록 삭제",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 11028
  },
  {
    "seq": 26,
    "id": "pri-networklist-history",
    "name": "과거 접속 Wi-Fi/유선 네트워크 프로필",
    "description": "과거에 연결했던 무선 공유기 SSID 및 네트워크 식별 프로필 목록 소거",
    "category": "Privacy",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 3285
  },
  {
    "seq": 27,
    "id": "pri-psreadline-history",
    "name": "PowerShell 콘솔 명령어 입력 기록",
    "description": "PowerShell 콘솔에서 입력했던 모든 스크립트/명령어 히스토리 파일(ConsoleHost_history.txt) 소거",
    "category": "Privacy",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 42697
  },
  {
    "seq": 28,
    "id": "brw-edge-cache",
    "name": "Microsoft Edge 웹 캐시",
    "description": "Edge 브라우저 임시 인터넷 파일 및 이미지 캐시 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 33913
  },
  {
    "seq": 29,
    "id": "brw-edge-history",
    "name": "Microsoft Edge 방문 기록",
    "description": "Edge 브라우저 URL 방문 이력 데이터베이스 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 10062
  },
  {
    "seq": 30,
    "id": "brw-edge-cookies",
    "name": "Microsoft Edge 쿠키/세션",
    "description": "Edge 브라우저 쿠키 및 사이트 저장 데이터 소거",
    "category": "Browser",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 34059
  },
  {
    "seq": 31,
    "id": "brw-chrome-cache",
    "name": "Google Chrome 웹 캐시",
    "description": "Chrome 브라우저 임시 인터넷 캐시 파일 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 35266
  },
  {
    "seq": 32,
    "id": "brw-chrome-history",
    "name": "Google Chrome 방문 기록",
    "description": "Chrome 브라우저 방문 이력 데이터베이스 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29974
  },
  {
    "seq": 33,
    "id": "brw-chrome-cookies",
    "name": "Google Chrome 쿠키/세션",
    "description": "Chrome 브라우저 저장 쿠키 및 로그인 세션 데이터 소거",
    "category": "Browser",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 21981
  },
  {
    "seq": 34,
    "id": "brw-edge-sessions",
    "name": "Edge 활성 세션 데이터",
    "description": "Edge 탭 복원 및 이전 세션 스냅샷 파일 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 24515
  },
  {
    "seq": 35,
    "id": "brw-chrome-gpu-cache",
    "name": "Chrome GPU 가속 캐시",
    "description": "Google Chrome 하드웨어 가속 셰이더 및 GPU 캐시 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 40123
  },
  {
    "seq": 36,
    "id": "brw-edge-media-cache",
    "name": "Edge 미디어 스트리밍 캐시",
    "description": "동영상 및 오디오 스트리밍 임시 버퍼 캐시 소거",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 50358
  },
  {
    "seq": 37,
    "id": "brw-chrome-downloads",
    "name": "Chrome 다운로드 이력",
    "description": "Chrome 브라우저 파일 다운로드 목록 기록 삭제 (실제 파일 유지)",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 4654
  },
  {
    "seq": 38,
    "id": "brw-chrome-shader-cache",
    "name": "Chrome 셰이더 컴파일 캐시",
    "description": "WebGL 및 캔버스 렌더링 셰이더 캐시 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 36913
  },
  {
    "seq": 39,
    "id": "brw-edge-dom-storage",
    "name": "Edge 로컬 스토리지(DOM)",
    "description": "Edge 브라우저 사이트별 로컬 DOM Storage 데이터 삭제",
    "category": "Browser",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 12484
  },
  {
    "seq": 40,
    "id": "brw-ie-temporary-files",
    "name": "Legacy IE 임시 인터넷 파일",
    "description": "구형 Internet Explorer/Trident 엔진 임시 웹 캐시 소거",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 33414
  },
  {
    "seq": 41,
    "id": "brw-ie-history-legacy",
    "name": "Legacy IE 방문 기록",
    "description": "구형 IE 브라우저 히스토리 기록 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 44333
  },
  {
    "seq": 42,
    "id": "brw-ie-form-data-legacy",
    "name": "Legacy IE 자동완성 양식",
    "description": "구형 IE 양식 자동 완성 데이터 초기화",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 49001
  },
  {
    "seq": 43,
    "id": "brw-autofill-cards",
    "name": "브라우저 양식 자동완성 & 결제 카드 정보",
    "description": "Chrome, Edge, Whale 등 브라우저에 자동 완성된 주소, 폼 입력값 및 결제 카드 DB 소거",
    "category": "Browser",
    "risk": "Deep",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 45277
  },
  {
    "seq": 44,
    "id": "brw-saved-passwords",
    "name": "브라우저 저장된 로그인 계정/비밀번호",
    "description": "Chrome, Edge, Whale 브라우저에 저장된 사이트 로그인 ID 및 비밀번호 DB(Login Data) 완전 소거",
    "category": "Browser",
    "risk": "Deep",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 40535
  },
  {
    "seq": 45,
    "id": "brw-kakaotalk-session",
    "name": "카카오톡 로컬 세션 & 자동 로그인 토큰",
    "description": "카카오톡 PC버전의 로컬 캐시, 사용자 프로필 세션 및 자동 로그인 토큰 데이터 완전 소거",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 34020
  },
  {
    "seq": 46,
    "id": "brw-discord-token",
    "name": "Discord 로그인 토큰 & 로컬 스토리지",
    "description": "Discord 데스크톱 앱의 자동 로그인 인증 토큰, 세션 스토리지 및 캐시 완전 소거",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 49623
  },
  {
    "seq": 47,
    "id": "brw-teams-slack-tokens",
    "name": "Teams & Slack 협업툴 로그인 세션",
    "description": "Microsoft Teams 및 Slack 데스크톱 클라이언트의 로컬 인증 세션 토큰 및 워크스페이스 캐시 삭제",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 50125
  },
  {
    "seq": 48,
    "id": "brw-cloud-drive-tokens",
    "name": "클라우드 드라이브 (OneDrive/Google/Dropbox)",
    "description": "OneDrive, Google Drive, Dropbox 클라이언트의 로컬 동기화 인덱스 및 세션 캐시 정리",
    "category": "Browser",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 44320
  },
  {
    "seq": 49,
    "id": "sec-defender-scan-logs",
    "name": "Defender 검사 이력 로그",
    "description": "Windows Defender 바이러스 검사 결과 히스토리 로그 소거",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 2680
  },
  {
    "seq": 50,
    "id": "sec-defender-quarantine",
    "name": "Defender 격리소 파일 소거",
    "description": "Defender에 의해 격리된 무효 악성코드 파편 영구 소거",
    "category": "Security",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 3728
  },
  {
    "seq": 51,
    "id": "sec-firewall-log-files",
    "name": "Windows 방화벽 로그",
    "description": "방화벽 패킷 드롭 및 연결 성공 로그 텍스트 파일 삭제",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 26260
  },
  {
    "seq": 52,
    "id": "sec-security-health",
    "name": "보안 상태 대시보드 캐시",
    "description": "Windows 보안 센터 대시보드 상태 알림 캐시 정리",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 21710
  },
  {
    "seq": 53,
    "id": "sec-defender-support",
    "name": "Defender 지원/진단 데이터",
    "description": "백신 오류 지원 보고서 및 진단 로그 파일 소거",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 48918
  },
  {
    "seq": 54,
    "id": "sec-audit-policy-logs",
    "name": "시스템 감사 보안 로그",
    "description": "보안 이벤트 로그 파일 일괄 비우기",
    "category": "Security",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 7639
  },
  {
    "seq": 55,
    "id": "sec-defender-signatures",
    "name": "구버전 백신 시그니처",
    "description": "새 버전 업데이트 후 잔류한 이전 바이러스 정의 파일 정리",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 38184
  },
  {
    "seq": 56,
    "id": "sec-vault-credentials",
    "name": "자격 증명 보관함 캐시",
    "description": "Windows Vault 임시 암호화 토큰 캐시 정리",
    "category": "Security",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 5875
  },
  {
    "seq": 57,
    "id": "sec-defender-reporting",
    "name": "Defender 보고 데이터",
    "description": "클라우드 진단 전송을 위한 로컬 백신 리포팅 캐시 삭제",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 5197
  },
  {
    "seq": 58,
    "id": "sec-smartscreen-logs",
    "name": "SmartScreen 검사 로그",
    "description": "다운로드 실행 파일에 대한 SmartScreen 필터 검사 로그 삭제",
    "category": "Security",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 4056
  },
  {
    "seq": 581,
    "id": "sec-ms-account-purge",
    "name": "Microsoft 계정 & Office WAM 토큰 소거 (강제 로그아웃)",
    "description": "Windows 자격 증명 관리자의 MicrosoftAccount/SSO_POP 토큰 및 WAM(IdentityCache/OneAuth/TokenBroker) 캐시를 소거하여 Office/Windows Live에서 강제 로그아웃합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 18420
  },
  {
    "seq": 582,
    "id": "sec-adobe-session-purge",
    "name": "Adobe Creative Cloud 계정 로그인 세션 & OOBE 소거",
    "description": "Adobe Creative Cloud, Photoshop, Acrobat의 OOBE 인증 토큰 및 로컬 세션 캐시를 소거하여 모든 Adobe 앱에서 즉시 로그아웃합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 32150
  },
  {
    "seq": 583,
    "id": "sec-autodesk-session-purge",
    "name": "Autodesk (AutoCAD) 로그인 상태 & 토큰 소거",
    "description": "AutoCAD 및 Autodesk 제품군의 Web Services LoginState.xml 세션 및 AdskIdentityManager 토큰을 초기화하여 로그아웃합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 14200
  },
  {
    "seq": 584,
    "id": "sec-edge-login-purge",
    "name": "Microsoft Edge 브라우저 로그인 세션 & Login Data 소거",
    "description": "Edge 브라우저 프로필의 자동 로그인 쿠키, Login Data(비밀번호), Token Service 및 탭 복원 세션을 소거하여 모든 사이트에서 로그아웃합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 24900
  },
  {
    "seq": 585,
    "id": "sec-chrome-login-purge",
    "name": "Google Chrome 브라우저 로그인 세션 & 동기화 토큰 소거",
    "description": "Google Chrome 브라우저의 구글 계정 동기화 토큰, 자동 로그인 쿠키, Login Data 및 세션을 초기화하여 모든 웹사이트에서 로그아웃합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 29800
  },
  {
    "seq": 586,
    "id": "sec-wincred-generic-purge",
    "name": "Windows 자격 증명 관리자 일반(Generic) 암호 일괄 소거",
    "description": "Windows 자격 증명 관리자에 자동 저장된 모든 일반 웹/앱/서버 로그인 자격 증명을 일괄 제거합니다. [특수 기능: 자동 선택 제외 / 전용 센터 연동]",
    "category": "Special",
    "subCategory": "Account",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 1240
  },
  {
    "seq": 587,
    "id": "spc-chrome-factory-reset",
    "name": "[공장초기화] Google Chrome 전체 프로필 & 데이터 영구 소거",
    "description": "Chrome 프로세스를 강제 종료하고 User Data 디렉터리를 완전 소거하여 최초 설치 상태(북마크/비밀번호/확장앱/캐시 완전 제거)로 초기화합니다. [특수 기능: 파괴적 작업 / 자동 선택 제외]",
    "category": "Special",
    "subCategory": "FactoryReset",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 185000
  },
  {
    "seq": 588,
    "id": "spc-edge-factory-reset",
    "name": "[공장초기화] Microsoft Edge 전체 프로필 & 데이터 영구 소거",
    "description": "Edge 프로세스를 강제 종료하고 User Data 디렉터리를 완전 소거하여 최초 설치 상태(북마크/비밀번호/확장앱/캐시 완전 제거)로 초기화합니다. [특수 기능: 파괴적 작업 / 자동 선택 제외]",
    "category": "Special",
    "subCategory": "FactoryReset",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 164000
  },
  {
    "seq": 589,
    "id": "spc-whale-factory-reset",
    "name": "[공장초기화] Naver Whale 전체 프로필 & 데이터 영구 소거",
    "description": "Whale 프로세스를 강제 종료하고 User Data 디렉터리를 완전 소거하여 최초 설치 상태(북마크/비밀번호/확장앱/캐시 완전 제거)로 초기화합니다. [특수 기능: 파괴적 작업 / 자동 선택 제외]",
    "category": "Special",
    "subCategory": "FactoryReset",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 142000
  },
  {
    "seq": 590,
    "id": "spc-firefox-factory-reset",
    "name": "[공장초기화] Mozilla Firefox 전체 프로필 & 데이터 영구 소거",
    "description": "Firefox 프로세스를 강제 종료하고 AppData/LocalAppData의 Firefox Profiles 폴더를 완전 소거하여 최초 설치 상태로 초기화합니다. [특수 기능: 파괴적 작업 / 자동 선택 제외]",
    "category": "Special",
    "subCategory": "FactoryReset",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 118000
  },
  {
    "seq": 591,
    "id": "spc-sync-default-user-profile",
    "name": "[기본 프로필 복제] 현재 사용자 설정을 Windows 기본 프로필(Default)로 복제",
    "description": "현재 계정의 테마, 작업표시줄, 탐색기 옵션, 바탕화면 레지스트리(reg save HKCU)를 C:\\Users\\Default로 복제하여 향후 생성되는 모든 신규 사용자 계정에 동일하게 자동 적용합니다. (기존 Default 프로필 자동 백업 및 Everyone/Users ACL 권한 자동 보정) [특수 기능: 시스템 템플릿 변경 / 자동 선택 제외]",
    "category": "Special",
    "subCategory": "Profile",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 32000
  },
  {
    "seq": 59,
    "id": "reg-mui-cache-clean",
    "name": "MUI 인터페이스 캐시",
    "description": "실행되었던 프로그램들의 다국어 셸 텍스트 레지스트리 캐시 정리",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 2203
  },
  {
    "seq": 60,
    "id": "reg-compat-flags",
    "name": "호환성 레이어 기록",
    "description": "이전 실행 앱에 임시 부여되었던 AppCompat 호환성 플래그 초기화",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 12833
  },
  {
    "seq": 61,
    "id": "reg-shell-ext-broken",
    "name": "셸 익스텐션 무효 파편",
    "description": "삭제된 프로그램의 탐색기 우클릭 셸 확장 레지스트리 참조 제거",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 41600
  },
  {
    "seq": 62,
    "id": "reg-firewall-orphans",
    "name": "방화벽 고립 규칙",
    "description": "이미 삭제된 프로그램 경로를 가리키는 유령 방화벽 허용 규칙 정리",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 41936
  },
  {
    "seq": 63,
    "id": "reg-clsid-orphans",
    "name": "고립된 CLSID 클래스 식별자",
    "description": "연결 대상 COM 서버/DLL이 존재하지 않는 고립 CLSID 레지스트리 정리",
    "category": "Registry",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 20210
  },
  {
    "seq": 64,
    "id": "reg-app-paths-invalid",
    "name": "무효 앱 실행 경로 (App Paths)",
    "description": "실행 파일이 삭제되었으나 레지스트리에 남아있는 App Paths 키 소거",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 1726
  },
  {
    "seq": 65,
    "id": "reg-shared-dlls",
    "name": "공유 DLL 잔여물",
    "description": "디스크에 존재하지 않는 공유 동적 라이브러리(SharedDlls) 카운터 정리",
    "category": "Registry",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 22474
  },
  {
    "seq": 66,
    "id": "reg-sound-events",
    "name": "무효 사운드 알림 이벤트",
    "description": "삭제된 애플리케이션이 등록해 둔 사운드 이벤트 연결 키 정리",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 22318
  },
  {
    "seq": 67,
    "id": "reg-font-associates",
    "name": "글꼴 연결 오류 수정",
    "description": "시스템 폰트 대체 목록 중 무효한 항목 정리",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 10200
  },
  {
    "seq": 68,
    "id": "reg-help-paths",
    "name": "도움말 파일 경로 파편",
    "description": "오래된 도움말 파일(HLP/CHM) 경로 레지스트리 잔재 제거",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 45082
  },
  {
    "seq": 69,
    "id": "reg-installer-fragments",
    "name": "인스톨러 분리 파편",
    "description": "삭제된 MSI 설치 패키지의 유령 레지스트리 키 정리",
    "category": "Registry",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 7098
  },
  {
    "seq": 70,
    "id": "reg-user-classes",
    "name": "사용자 클래스 파편",
    "description": "HKCU Software Classes 내의 빈 하위 키 정리",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 27308
  },
  {
    "seq": 71,
    "id": "reg-run-keys-invalid",
    "name": "자동 실행 무효 키",
    "description": "삭제된 프로그램이 Run 레지스트리에 남겨둔 시작 프로그램 찌꺼기 제거",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 3233
  },
  {
    "seq": 72,
    "id": "reg-start-menu-links",
    "name": "시작 메뉴 무효 바로가기",
    "description": "시작 메뉴 프로그램 목록 중 대상이 없는 빈 LNK 바로가기 제거",
    "category": "Registry",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 6725
  },
  {
    "seq": 73,
    "id": "reg-typelib-orphans",
    "name": "TypeLib 분리 파편",
    "description": "참조 대상이 없는 고립된 TypeLib 레지스트리 인터페이스 정의 소거",
    "category": "Registry",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 44968
  },
  {
    "seq": 74,
    "id": "upd-cache-clean",
    "name": "업데이트 다운로드 캐시",
    "description": "설치 완료된 Windows Update 다운로드 임시 패키지 소거",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 45983
  },
  {
    "seq": 75,
    "id": "upd-winsxs-reset",
    "name": "WinSxS 정밀 압축/청소",
    "description": "DISM을 통한 대체된 구버전 구성요소 백업 정리 및 베이스라인 리셋",
    "category": "Update",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 28350
  },
  {
    "seq": 76,
    "id": "upd-delivery-opt",
    "name": "전송 최적화 캐시 (Delivery Optimization)",
    "description": "P2P 업데이트 공유를 위해 저장된 로컬 전송 최적화 캐시 파일 삭제",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 13461
  },
  {
    "seq": 77,
    "id": "upd-bits-queue-reset",
    "name": "BITS 전송 대기열 초기화",
    "description": "백그라운드 지능형 전송 서비스 대기열 초기화",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 40812
  },
  {
    "seq": 78,
    "id": "upd-windows-old-del",
    "name": "이전 Windows 설치본 (Windows.old)",
    "description": "대규모 기능 업데이트 후 잔류한 이전 OS 롤백용 거대 폴더 삭제",
    "category": "Update",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 13365
  },
  {
    "seq": 79,
    "id": "upd-driver-store-tmp",
    "name": "드라이버 설치 임시 잔해",
    "description": "DriverStore 설치 중 생성된 임시 압축 해제 잔해 소거",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 34154
  },
  {
    "seq": 80,
    "id": "upd-msi-patch-cache",
    "name": "MSI 패치 백업 캐시",
    "description": "윈도우 인스톨러 $PatchCache$ 폴더 내의 백업 패치 데이터 정리",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 50042
  },
  {
    "seq": 81,
    "id": "upd-cbs-logs-all",
    "name": "CBS 매니페스트 로그",
    "description": "Windows 서비스 및 업데이트 처리 CBS(Component-Based Servicing) 로그 소거",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 14694
  },
  {
    "seq": 82,
    "id": "upd-store-cache-dat",
    "name": "Store 패키지 데이터 캐시",
    "description": "SoftwareDistribution DataStore 데이터베이스 임시 트랜잭션 파일 정리",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 44111
  },
  {
    "seq": 83,
    "id": "upd-pending-rename",
    "name": "파일 이름 변경 대기열 소거",
    "description": "재부팅 시 처리 예정으로 남아있는 잔여 파일 이름 변경 대기열 초기화",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 44573
  },
  {
    "seq": 84,
    "id": "upd-manifest-cache",
    "name": "컴포넌트 매니페스트 캐시",
    "description": "WinSxS 내부 ManifestCache 임시 참조 데이터 정리",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 23112
  },
  {
    "seq": 85,
    "id": "upd-reboot-required",
    "name": "시스템 재부팅 보류 플래그 초기화",
    "description": "업데이트 완료 후 남아있는 불필요한 RebootRequired 플래그 정리",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 4090
  },
  {
    "seq": 86,
    "id": "upd-wu-text-logs",
    "name": "Windows Update 텍스트 로그",
    "description": "루트 디렉터리의 레거시 WindowsUpdate.log 텍스트 로그 삭제",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 44870
  },
  {
    "seq": 87,
    "id": "upd-office-temp-cache",
    "name": "Office 배포 패키지 캐시",
    "description": "MS Office 업데이트 설치 시 다운로드된 임시 압축 해제 캐시 삭제",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 35840
  },
  {
    "seq": 88,
    "id": "upd-sqm-data-all",
    "name": "SQM 품질 개선 통계 데이터",
    "description": "서비스 프로필에 저장된 Windows 소프트웨어 품질 메트릭스 파일 삭제",
    "category": "Update",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 17656
  },
  {
    "seq": 89,
    "id": "sys-dns-cache-flush",
    "name": "DNS 해석기 캐시 초기화",
    "description": "로컬 DNS 리졸버 캐시를 비워 도메인 해석 속도 및 최신 IP 반영",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 40117
  },
  {
    "seq": 90,
    "id": "sys-icon-cache-reset",
    "name": "시스템 아이콘 캐시 재생성",
    "description": "손상되었거나 깨진 파일/프로그램 아이콘 캐시 파일(IconCache.db) 재생성",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 1074
  },
  {
    "seq": 91,
    "id": "sys-shader-cache",
    "name": "DirectX 그래픽 셰이더 캐시",
    "description": "D3DSCache 폴더에 컴파일되어 적체된 구형 DirectX 셰이더 캐시 소거",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 19734
  },
  {
    "seq": 92,
    "id": "sys-net-stack-reset",
    "name": "네트워크 스택 / IP 리셋",
    "description": "TCP/IP 및 Winsock 스택을 초기화하여 네트워크 지연 및 핑 안정화",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 11717
  },
  {
    "seq": 93,
    "id": "sys-spooler-reset",
    "name": "프린터 인쇄 대기열 초기화",
    "description": "인쇄 오류로 멈춘 스풀러 서비스 및 대기열(PRINTERS) 임시 파일 강제 초기화",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 8149
  },
  {
    "seq": 94,
    "id": "sys-wsreset-cache",
    "name": "MS Store 서비스 캐시 리셋",
    "description": "Microsoft Store 앱의 실행 장애 및 캐시 리셋 (wsreset)",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 39962
  },
  {
    "seq": 95,
    "id": "sys-timesync-all",
    "name": "표준 시간 서버 동기화",
    "description": "Windows Time 서비스 표준 시간 서버 즉시 동기화",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 1657
  },
  {
    "seq": 96,
    "id": "sys-wmi-salvage",
    "name": "WMI 관리 데이터베이스 정합성 검사",
    "description": "손상된 WMI 저장소 점검 및 자동 복구 (salvagerepository)",
    "category": "System",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 1898
  },
  {
    "seq": 97,
    "id": "sys-winhttp-proxy",
    "name": "시스템 프록시 구성 초기화",
    "description": "악성코드나 비정상 종료로 잘못 설정된 WinHTTP 프록시를 다이렉트로 초기화",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 21291
  },
  {
    "seq": 98,
    "id": "sys-arp-cache-flush",
    "name": "ARP 테이블 캐시 초기화",
    "description": "로컬 라우터 및 네트워크 ARP 캐시 테이블을 비워 네트워크 충돌 해결",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 30974
  },
  {
    "seq": 99,
    "id": "sys-perf-counters",
    "name": "성능 측정 카운터 리셋",
    "description": "손상된 시스템 리소스 모니터 성능 카운터 레지스트리 복원 (lodctr /r)",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 49187
  },
  {
    "seq": 100,
    "id": "sys-com-catalog-reset",
    "name": "COM+ 구성 카탈로그 캐시 정리",
    "description": "Registration 폴더 내의 COM+ 임시 카탈로그 백업 파일 정리",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 22839
  },
  {
    "seq": 101,
    "id": "sys-winsock-reset",
    "name": "Winsock 소켓 카탈로그 리셋",
    "description": "Winsock 레이어 소켓 프로토콜 카탈로그 전체 기본값 복원",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29365
  },
  {
    "seq": 102,
    "id": "sys-system32-temp",
    "name": "System32 루트 임시 파일",
    "description": "C:\\\\Windows\\\\System32\\\\Temp 폴더 내의 시스템 프로세스 잔여물 소거",
    "category": "System",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 26768
  },
  {
    "seq": 103,
    "id": "sys-event-logs-clear",
    "name": "Windows 전체 이벤트 로그 비우기",
    "description": "용량을 차지하는 누적된 애플리케이션 및 시스템 이벤트 로그 전체 비우기",
    "category": "System",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 34789
  },
  {
    "seq": 104,
    "id": "stg-windows-temp",
    "name": "Windows 공용 임시 폴더 (%WinDir%\\\\Temp)",
    "description": "윈도우 운영체제 공용 임시 디렉터리 내의 잔여 파일 완전 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 22058
  },
  {
    "seq": 105,
    "id": "stg-user-temp-data",
    "name": "사용자 프로필 임시 폴더 (%TEMP%)",
    "description": "현재 로그인 사용자 계정의 임시 파일 디렉터리 일괄 비우기",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 36507
  },
  {
    "seq": 106,
    "id": "stg-recycle-bin-all",
    "name": "모든 드라이브 휴지통 완전 비우기",
    "description": "C, D 등 모든 시스템 드라이브의 휴지통 파일 영구 무음 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 9950
  },
  {
    "seq": 107,
    "id": "stg-crash-memory-dump",
    "name": "시스템 전체 메모리 덤프 (MEMORY.DMP)",
    "description": "블루스크린(BSOD) 발생 시 디스크에 생성된 수 GB 크기의 메모리 덤프 파일 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 13457
  },
  {
    "seq": 108,
    "id": "stg-prefetch-all",
    "name": "Prefetch 가속 캐시 정리",
    "description": "Windows\\\\Prefetch 내의 구형 프로그램 가속 캐시 파일 정리",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 38613
  },
  {
    "seq": 109,
    "id": "stg-wer-reports",
    "name": "사용자 계정 오류 보고서 (WER)",
    "description": "Windows 오류 보고 서비스(WER)에 누적된 크래시 로그 및 메모리 스냅샷 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 46898
  },
  {
    "seq": 110,
    "id": "stg-app-crash-dumps",
    "name": "개별 앱 크래시 덤프 (CrashDumps)",
    "description": "서드파티 애플리케이션 오류 시 생성된 미니 덤프(.dmp) 파일 정리",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 8492
  },
  {
    "seq": 111,
    "id": "stg-font-render-cache",
    "name": "시스템 글꼴 렌더링 캐시",
    "description": "Windows FontCache 서비스의 손상되거나 비대해진 글꼴 렌더링 캐시 초기화",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 48665
  },
  {
    "seq": 112,
    "id": "stg-iis-log-files",
    "name": "IIS 웹 서버 로그 파일",
    "description": "로컬 IIS 웹 서버 로그 디렉터리(inetpub\\\\logs) 잔여 데이터 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 38868
  },
  {
    "seq": 113,
    "id": "stg-catroot2-cleanup",
    "name": "암호화 카탈로그 저장소 캐시 (Catroot2)",
    "description": "CryptSvc 서명 카탈로그 임시 트랜잭션 파일 초기화",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 34292
  },
  {
    "seq": 114,
    "id": "stg-nvidia-gl-cache",
    "name": "NVIDIA OpenGL 셰이더 캐시",
    "description": "NVIDIA 그래픽 카드 드라이버 OpenGL/Vulkan 셰이더 캐시 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 49455
  },
  {
    "seq": 115,
    "id": "stg-directx-shader",
    "name": "DirectX 범용 셰이더 캐시",
    "description": "DirectX 게임 플레이 중 생성된 셰이더 컴파일 캐시 정리",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 41251
  },
  {
    "seq": 116,
    "id": "stg-minidumps-all",
    "name": "시스템 미니덤프 진단 요약본 (Minidump)",
    "description": "C:\\\\Windows\\\\Minidump 내의 소형 크래시 분석 파일들 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29264
  },
  {
    "seq": 117,
    "id": "stg-inf-install-logs",
    "name": "드라이버 설치 이력 로그 (setupapi.dev.log)",
    "description": "장치 드라이버 설치 과정에서 적체된 거대 로그 텍스트 파일 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 40316
  },
  {
    "seq": 118,
    "id": "stg-bits-cache",
    "name": "BITS 백그라운드 전송 캐시",
    "description": "ProgramData Network Downloader 임시 큐 파일 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 30768
  },
  {
    "seq": 119,
    "id": "stg-package-cache",
    "name": "대형 앱 패키지 설치 캐시",
    "description": "Visual Studio / C++ Redistributable 등 인스톨러 캐시 정리",
    "category": "Storage",
    "risk": "Deep",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 35404
  },
  {
    "seq": 120,
    "id": "stg-setupapi-breadcrumb",
    "name": "장치 드라이버 로딩 로그",
    "description": "Windows inf 폴더 내의 잔여 드라이버 셋업 로그 정리",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 15862
  },
  {
    "seq": 121,
    "id": "stg-win-logfiles-all",
    "name": "Windows 범용 시스템 로그",
    "description": "System32 LogFiles 폴더 내의 각종 서비스 텍스트 로그 파일 일괄 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 39961
  },
  {
    "seq": 122,
    "id": "stg-desktop-bridge",
    "name": "데스크톱 브릿지 가상화 데이터",
    "description": "UWP / MSIX 가상화 앱 레포지토리의 임시 패키지 캐시 삭제",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 32929
  },
  {
    "seq": 123,
    "id": "stg-dism-work-logs",
    "name": "DISM 이미지 복구 작업 로그",
    "description": "DISM 명령어 수행 시 기록된 디버깅 텍스트 로그 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 32074
  },
  {
    "seq": 124,
    "id": "stg-local-temp-extra",
    "name": "AppData 로컬 임시 잔해 (%LocalAppData%\\\\Temp)",
    "description": "각종 프로그램이 AppData\\\\Local\\\\Temp에 생성해 둔 임시 파일 완전 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 22436
  },
  {
    "seq": 125,
    "id": "stg-was-activation",
    "name": "WAS 서비스 실행 로그",
    "description": "Windows Process Activation Service 로그 파일 정리",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 15906
  },
  {
    "seq": 126,
    "id": "stg-msi-installer-tmp",
    "name": "MSI 인스톨러 임시 데이터",
    "description": "C:\\\\Windows\\\\Installer 폴더 내의 .tmp 확장자 임시 파일 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 16293
  },
  {
    "seq": 127,
    "id": "stg-sys-profile-temp",
    "name": "시스템 프로필 전용 임시 파일",
    "description": "LocalService 및 NetworkService 프로필 임시 폴더 잔여물 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 18008
  },
  {
    "seq": 128,
    "id": "stg-global-wer-clear",
    "name": "전체 오류 보고 통합 저장소",
    "description": "ProgramData Microsoft WER 통합 크래시 저장소 완전 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 46535
  },
  {
    "seq": 129,
    "id": "stg-hiberfil-toggle",
    "name": "최대 절전 모드 파일 (hiberfil.sys) 해제",
    "description": "최대 절전 모드를 비활성화하여 물리 RAM 크기(16GB~64GB)만큼의 C: 시스템 디스크 공간 즉시 회수",
    "category": "Storage",
    "risk": "Deep",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 39025
  },
  {
    "seq": 130,
    "id": "stg-dism-resetbase",
    "name": "DISM WinSxS 컴포넌트 베이스라인 리셋",
    "description": "구버전 윈도우 업데이트 컴포넌트 백업을 영구 정리 및 압축하여 3GB~10GB 대용량 공간 확보",
    "category": "Storage",
    "risk": "Deep",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 43537
  },
  {
    "seq": 131,
    "id": "stg-driver-store-backup",
    "name": "DriverStore 구버전 드라이버 백업 정리",
    "description": "DriverStore FileRepository에 누적된 구버전 그래픽/오디오 드라이버 패키지 소거",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 37804
  },
  {
    "seq": 132,
    "id": "stg-wsearch-edb-shrink",
    "name": "Windows Search 색인 DB (Windows.edb) 압축",
    "description": "수 GB로 비대해진 Windows Search 인덱싱 데이터베이스를 초기화하여 대용량 공간 회수",
    "category": "Storage",
    "risk": "Safe",
    "selected": true,
    "status": "Pending",
    "estimatedKb": 29769
  },
  {
    "seq": 133,
    "id": "stg-cipher-zero-wipe",
    "name": "디스크 빈 공간 난수 덮어쓰기 (자유 공간 포렌식 와이핑)",
    "description": "이미 삭제된 파일들의 복구 프로그램(Recuva 등)을 통한 복원을 원천 차단하기 위해 자유 공간에 0x00 난수 덮어쓰기 [특수 기능: 자동 선택 제외]",
    "category": "Special",
    "subCategory": "Forensics",
    "risk": "Risky",
    "selected": false,
    "status": "Pending",
    "estimatedKb": 44896
  }
];
